# Generated by Django 5.2.6 on 2025-09-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('age_group', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('relationship', models.CharField(default='Single', max_length=20)),
                ('born_again', models.BooleanField(default=False)),
                ('membership', models.BooleanField(default=False)),
                ('heard_through', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted', models.BooleanField(default=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
