# Generated by Django 5.2.6 on 2025-09-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='address',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='heard_through',
            new_name='heard_from',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='submitted',
        ),
        migrations.AddField(
            model_name='guest',
            name='country_code',
            field=models.CharField(default='NG', max_length=10),
        ),
        migrations.AddField(
            model_name='guest',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='status',
            field=models.CharField(default='Submitted'),
        ),
        migrations.AddField(
            model_name='guest',
            name='street_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='born_again',
            field=models.CharField(default='No'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='membership',
            field=models.CharField(default='No'),
        ),
    ]
