# Generated by Django 5.2.6 on 2025-09-15 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_rename_address_guest_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 15, 6, 55, 13, 24038, tzinfo=datetime.timezone.utc)),
        ),
    ]
