# Generated by Django 5.2.6 on 2025-09-15 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_alter_guest_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
